services:
  kroki:
    image: yuzutech/kroki:0.24.1
    ports:
      - ${KROKI_PORT:-8125}:8000
    env_file:
      - path: .env
        required: true  # default is true

  scrape-and-plot:
    build: .
    volumes:
      - ${EBD_DOCX_FILE}:/container/ebd.docx
      - ${OUTPUT_DIR}:/container/output
    env_file:
      - path: .env
        required: true  # default is true
   