services:
  kroki:
    image: yuzutech/kroki:0.24.1
    ports:
      - ${KROKI_PORT:-8125}:8000
    env_file:
      - path: .env
        required: true  # default is true

  scrape-and-plot:
    build: .
    image: ghcr.io/hochfrequenz/ebd_toolchain:latest
    # If you run into 'manifest unknown' during docker pull, try replacing `:latest` with `:v1.2.3`.
    # where v1.2.3 is the latest version of the GHCR image, which can be found here:
    # https://github.com/Hochfrequenz/ebd_toolchain/pkgs/container/ebd_toolchain
    volumes:
      - ${EBD_DOCX_FILE}:/container/ebd.docx
      - ${OUTPUT_DIR}:/container/output
    env_file:
      - path: .env
        required: true  # default is true
