name: "Coverage"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: 3.14
      - name: Install dependencies
        run: uv sync --group coverage
      - name: Create .env file
        run: uv run python create_env_file.py
      - name: Start containers
        run: docker compose up -d
      - name: Run Tests and Record Coverage
        working-directory: unittests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          uv run coverage run -m pytest
          uv run coverage html --omit unittests/*
          uv run coverage report --fail-under 43 --omit unittests/*
